version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
        name: NPM install
        command: npm install --save
      - run:
        name: Run test
        command: npm run test
  # deploy:
  #   docker:
  #     - image: circleci/node:7.10
  #   steps:
  #     - checkout
  #     - run: 
  #       name: NPM install
  #       command: |
  #         npm install --save

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
      # - deploy:
      #     requires:
      #       - build
      #       - test