version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --save
      - run: npm install browserify
      - run: mkdir dist
      - run:  npm run build
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --save
      - run: npm run test
  # deploy:
  #   docker:
  #     - image: circleci/node:7.10
  #   steps:
  #     - checkout
  #     - run: 
  #       name: NPM install
  #       command: |
  #         npm install --save

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
      # - deploy:
      #     requires:
      #       - build
      #       - test