version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install --save
      - run: sudo npm install -g
      - run: sudo npm install --save mocha
      - run: sudo npm install --save puppeteer
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules 
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: sudo apt install libnss3-dev
      - run: sudo apt-get install libatk-bridge2.0-0
      - run: sudo apt-get install libxkbcommon-x11-0
      - run: sudo apt-get install -y libgbm-dev
      - run: sudo apt install libgtk-3-0
      - run: sudo apt-get install libasound2
      - run: npm run test 

orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  version: 2.1
  Build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - test